### ISSUE TITLE
Update Status Function crashing when giving no input

### ISSUE THREAD

**Issue by BrandonFirmstone** [BrandonFirmstone/ProjectTerminal#2]
**Describe the bug**
After going to the Update Status function, after it shows you all tasks it crashes giving the error in the additional context section.
This is due to an issue with the job_selection() function.

**Expected behavior**
It should ask the user for their input again.

**Additional context**

Traceback (most recent call last):
  File "run.py", line 345, in <module>
    print("P R O J E C T \nT E R M I N A L\n")
  File "run.py", line 326, in main_menu
    new_job = Job()
  File "run.py", line 134, in view_due_jobs
    return_to_menu()
  File "run.py", line 223, in return_to_menu
    '''
  File "run.py", line 326, in main_menu
    new_job = Job()
  File "run.py", line 134, in view_due_jobs
    return_to_menu()
  File "run.py", line 223, in return_to_menu
    '''
  File "run.py", line 321, in main_menu
    elif user_selection == 2 or user_selection == "2":
  File "run.py", line 146, in print_all_jobs
    return_to_menu()
  File "run.py", line 223, in return_to_menu
    '''
  File "run.py", line 326, in main_menu
    new_job = Job()
  File "run.py", line 134, in view_due_jobs
    return_to_menu()
  File "run.py", line 223, in return_to_menu
    '''
  File "run.py", line 330, in main_menu
    elif user_selection == 6 or user_selection == "6":
  File "run.py", line 246, in update_status
    Makes the change in the all_jobs dataframe and then writes over the jobs.csv file using the amended dataframe.  #  noqa
  File "run.py", line 210, in job_selection
    print(all_jobs.to_string())
ValueError: invalid literal for int() with base 10: ''

**Comment by BrandonFirmstone** [comment]
First attempt to fix:

Changing: if (all_jobs.index == user_selection).any() is False:
To: if (all_jobs.index == user_selection).any() is False or user_selection == '':

This should check that the user has at least entered something.

Result: It still crashed because it is trying to convert the input to an integer.

Second attempt to fix:

Moving index_selected = int(user_selection) after the if statement checking user_selection

Result: Now works as expected.
